# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '2'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  queue:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile-dev
      args:
        rails_env: docker-dev
    image: nrel/openstudio-server:latest
    env_file:
      - ../../.env
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    links:
      - db
      - rserve
      - queue
    ports:
      - "8080:3000"
    mem_limit: 12g
    volumes:
      - osdata:/mnt/openstudio
      - ../..:/opt/openstudio/
  web-background:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile-dev
      args:
        rails_env: docker-dev
    image: nrel/openstudio-server:latest
    env_file:
      - ../../.env
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
      - QUEUE=analyses,background,analysis_wrappers
    links:
      - db
      - rserve
      - queue
    volumes:
      - osdata:/mnt/openstudio
      - ../..:/opt/openstudio/
    # TODO: This is not using the wait-for-it script, not sure if we still want this file.
    command: bundle exec rake resque:work
  worker:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile-dev
      args:
        rails_env: docker-dev
    image: nrel/openstudio-server:latest
    env_file:
      - ../../.env
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
      - QUEUE=simulations
    links:
      - web
      - db
      - rserve
      - queue
    volumes:
      - ../..:/opt/openstudio/
    command: bundle exec rake resque:work
  rserve:
    build: ../../docker/R
    image: nrel/openstudio-rserve:latest
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    volumes:
      - osdata:/mnt/openstudio
volumes:
  osdata:
    external: true
