# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  is_windows = (RUBY_PLATFORM =~ /mswin|mingw|cygwin/)
  use_nfs = !is_windows
  use_nfs = false if ENV["VAGRANT_DISABLE_NFS"] == "true"

  # Don't use 11.14.2 because of https://github.com/opscode/chef/issues/1739 (duplicate error)
  # Latest is 11.16.2
  config.omnibus.chef_version = :latest
  #config.omnibus.chef_version = "11.12.8"

  # Use berkshelf.  Make sure to install ChefDK if you are using Windows.
  # config.berkshelf.enabled = true

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  #config.vm.network :forwarded_port, guest: 27017, host: 8888
  config.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.11"
  config.vm.hostname = "os-worker-1"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder "../../", "/vagrant", :nfs => !is_windows
  config.vm.synced_folder "../../worker-nodes", "/data/worker-nodes", :nfs => use_nfs
  config.vm.synced_folder "../../launch-instance", "/data/launch-instance", :nfs => use_nfs
  config.vm.synced_folder "../../lib/R-packages", "/data/R-packages", :nfs => use_nfs
  # config.vm.synced_folder "../../../OpenStudio-workflow", "/data/OpenStudio-workflow", :nfs => use_nfs
  # config.vm.synced_folder "../../../OpenStudio-analysis-gem", "/data/OpenStudio-analysis-gem", :nfs => use_nfs
  # config.vm.synced_folder "E:/data-worker", "/mnt/openstudio", :nfs => use_nfs, :owner => "vagrant", :group => "www-data", :mount_options => [ "dmode=775", "fmode=775" ]

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", 1024*2, "--cpus", 1*2]

    # Disable DNS proxy -- Causes slowness: https://github.com/rubygems/rubygems/issues/513
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vm.provider :aws do |aws, override|
    begin
      override.vm.box = "dummy"
      override.vm.box_url = "http://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

      # you will need to create a yaml file with these values to
      # properly deploy to ec2
      require 'yaml'
      secret_file = File.join(Dir.home, '.aws', 'config.yml')
      if File.exist? secret_file
        aws_config = YAML::load_file(secret_file)
        aws.access_key_id = aws_config.fetch("access_key_id")
        aws.secret_access_key = aws_config.fetch("secret_access_key")
        aws.keypair_name = aws_config.fetch("keypair_name")
        aws.region = aws_config.fetch("region")
        override.ssh.private_key_path = aws_config.fetch("private_key_path")
        aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 16 }]
      else
        raise "Could not find '#{secret_file}' file with your secrets"
      end

      aws.security_groups = ["default"]
      aws.region = "us-east-1"
      aws.instance_type = "m3.xlarge" # $0.45 / hour, 4 cores, moderate network
      #aws.instance_type = "m3.medium" # $0.07 / hour, 1 core, slow network

      aws.ami = "ami-9eaa1cf6"  # Ubuntu 14.04 HVM EBS-SSD

      override.ssh.username = "ubuntu"

      aws.tags = {
          'Name' => 'Vagrant OpenStudio-worker',
          'NodeType' => 'Worker',
          'UserUUID' => ENV["VAGRANT_AWS_USER_UUID"] || 'unknown_user_uuid'
      }
    rescue LoadError
      warn "Unable to configure AWS provider."
    end
  end

  config.vm.provision :chef_solo do |chef|
    chef.log_level = :info
    chef.cookbooks_path = "../chef/cookbooks"
    chef.roles_path = "../chef/roles"

    chef.add_role "openstudio-worker"
  end
end
