# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  is_windows = (RUBY_PLATFORM =~ /mswin|mingw|cygwin/)
  use_nfs = !is_windows
  use_nfs = false if ENV['VAGRANT_DISABLE_NFS'] == 'true'

  # Don't use 11.14.2 because of https://github.com/opscode/chef/issues/1739 (duplicate error)
  config.omnibus.chef_version = 'latest'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'ubuntu/trusty64'

  # Use berkshelf.  Make sure to install ChefDK if you are using Windows.
  config.berkshelf.enabled = true

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 27017, host: 8888
  config.vm.network :forwarded_port, guest: 22, host: 2201, id: 'ssh'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: '192.168.33.11'
  config.vm.hostname = 'os-worker-1'

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../../", "/vagrant", :nfs => !is_windows
  config.vm.synced_folder '../../worker-nodes', '/data/worker-nodes', nfs: use_nfs
  config.vm.synced_folder '../../launch-instance', '/data/launch-instance', nfs: use_nfs
  config.vm.synced_folder '../../lib/R-packages', '/data/R-packages', nfs: use_nfs

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ['modifyvm', :id, '--memory', 1024 * 2, '--cpus', 1 * 2]

    # Disable DNS proxy -- Causes slowness: https://github.com/rubygems/rubygems/issues/513
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
  end

  config.vm.provider :aws do |aws, override|
    begin
      override.vm.box = 'dummy'
      override.vm.box_url = 'http://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'
      override.nfs.functional = false

      # you will need to create a yaml file with these values to
      # properly deploy to ec2
      secret_file = File.join(Dir.home, '.aws', 'config.yml')
      if ENV['AWS_ACCESS_KEY'] && !File.exist?(secret_file)
        fail "[ERROR] AWS secrets are set in your environment, but need more information in #{secret_file}"
      elsif File.exist? secret_file
        require 'yaml'
        aws_config = YAML.load_file(secret_file)
        aws.access_key_id = aws_config.fetch('access_key_id')
        aws.secret_access_key = aws_config.fetch('secret_access_key')
        aws.keypair_name = aws_config.fetch('keypair_name')
        aws.region = aws_config.fetch('region')
        override.ssh.private_key_path = aws_config.fetch('private_key_path')
        aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 16 }]
      else
        warn "[WARNING] Could not find '#{secret_file}' file with access keys. Assuming no AWS provider, will continue..."
      end

      aws.security_groups = ['default']
      aws.region = 'us-east-1'
      # http://www.ec2instances.info/
      # aws.instance_type = "m3.medium" # $0.07 / hour, 1 core, slow network
      aws.instance_type = 'm3.large' # $0.14 / hour, 2 cores, moderate network
      # aws.instance_type = "m3.xlarge" # $0.28 / hour, 4 cores, moderate network

      aws.ami = 'ami-9eaa1cf6'  # Ubuntu 14.04 HVM EBS-SSD

      override.ssh.username = 'ubuntu'

      aws.tags = {
        'Name' => 'Vagrant OpenStudio-worker',
        'NodeType' => 'Worker',
        'UserUUID' => ENV['VAGRANT_AWS_USER_UUID'] || 'unknown_user_uuid'
      }
    rescue LoadError
      warn 'Unable to configure AWS provider.'
    end
  end

  config.vm.provision :chef_solo do |chef|
    chef.log_level = :info
    chef.roles_path = '../chef/roles'

    chef.add_role 'openstudio-worker'
  end
end
