AllCops:
  Exclude:
    - 'launch-instance/**/*'
    - 'lib/**/*'
    - 'prototyping/**/*'
    - 'testing/**/*'

Rails/DefaultScope:
  Include:
    - 'server/**/*.rb'

inherit_from: .rubocop_todo.yml

# ==================== Linters ====================
Lint/AmbiguousOperator:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

# Offense count: 1
Lint/UnreachableCode:
  Enabled: false

# Offense count: 51
Lint/UselessAssignment:
  Enabled: true

# ==================== Styles ====================
# Offense count: 4
Metrics/BlockNesting:
  Max: 4

# Offense count: 18
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 500

# Offense count: 27
Metrics/CyclomaticComplexity:
  Max: 48

# Offense count: 974
Metrics/LineLength:
  Max: 1200

# Offense count: 87
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 350

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 8

# ==================== Disabled on Purpose ====================
# Offense count: 3
Style/AccessorMethodName:
  Enabled: true

# Need to allow indented case statements
# Offense count: 9
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Offense count: 18
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 2
Style/ClassVars:
  Enabled: false

# Offense count: 42
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/EachWithObject:
  Enabled: false

# Offense count: 2
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 7
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Offense count: 17
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Do NOT enable.  For some reason this is catchy any next which I feel are okay.
# Offense count: 18
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/Next:
  Enabled: false

# Do NOT enable this because it appears $? is different than $CHILD_STATUS.
# Offense count: 7
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

