AllCops:
  Exclude:
    - 'launch-instance/**/*'
    - 'lib/**/*'
    - 'prototyping/**/*'
    - 'testing/**/*'
    - 'vagrant/**/*'

Rails/DefaultScope:
  Include:
    - 'server/**/*.rb'

inherit_from: .rubocop_todo.yml