AllCops:
  Exclude:
    - 'server/spec/files/**/*'
    - 'server/lib/delayed/heartbeat/**/*'
    - 'server/vendor/bundle/**/*'
    - 'lib/update_license.rb'
    - 'server/gems/**/*'
    - 'gems/**/*'

Security/YAMLLoad:
  Enabled: false

inherit_from:
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop_v3.yml
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop-rails.yml
