AllCops:
  Exclude:
    - 'server/spec/files/**/*'
    - 'server/lib/delayed/heartbeat/**/*'
    - 'server/vendor/bundle/**/*'

Rails:
  Enabled: true

# ==================== Linters ====================
Lint/AmbiguousOperator:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/UnreachableCode:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

# ==================== Styles ====================
Metrics/BlockNesting:
  Max: 4

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 48

Metrics/LineLength:
  Max: 1200

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 350

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 8

# ==================== Disabled on Purpose ====================
# Mongoid doesn't like find_each.
Rails/FindEach:
  Enabled: false

Style/AccessorMethodName:
  Enabled: true

# Need to allow indented case statements
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Do NOT enable.  For some reason this is catching any next which I feel are okay.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/Next:
  Enabled: false

# Do NOT enable this because it appears $? is different than $CHILD_STATUS.
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

# a = if true
#       1
#     else
#       2
#     end
Style/ConditionalAssignment:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
  Enabled: true

# 27000 => 27_000
Style/NumericLiterals:
  Enabled: false
