#*******************************************************************************
# OpenStudio(R), Copyright (c) 2008-2016, Alliance for Sustainable Energy, LLC.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# (1) Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# (2) Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# (3) Neither the name of the copyright holder nor the names of any contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission from the respective party.
#
# (4) Other than as required in clauses (1) and (2), distributions in any form
# of modifications or other derivative works may not use the "OpenStudio"
# trademark, "OS", "os", or any other confusingly similar designation without
# specific prior written permission from Alliance for Sustainable Energy, LLC.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER, THE UNITED STATES
# GOVERNMENT, OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#*******************************************************************************

#
# Cookbook Name:: openstudio_server
# Recipe:: bashprofile
#

ruby_block 'update bash_profile' do
  block do
    bash_filename = nil
    if platform_family?('debian')
      bash_filename = "/home/#{node[:openstudio_server][:bash_profile_user]}/.bash_aliases"
    else
      bash_filename = "/home/#{node[:openstudio_server][:bash_profile_user]}/.bash_profile"
    end

    unless File.exist?(bash_filename)
      File.open(bash_filename, 'w') { |f| f << '# Chef autocreated bash_profile' }
    end

    file = Chef::Util::FileEdit.new(bash_filename)

    file.insert_line_if_no_match(
      '# Useful aliases. Generated by Chef',
      ["\n# Useful aliases. Generated by Chef",
       "alias ls='ls --color=auto'",
       "alias ll='ls -la'",
       "alias l.='ls -d .* --color=auto'",
       "alias ..='cd ..'",
       "alias ...='cd ../../../'",
       "alias ....='cd ../../../../'",
       "alias .....='cd ../../../../'",
       "alias .4='cd ../../../../'",
       "alias .5='cd ../../../../..'",
       "alias grep='grep --color=auto'",
       "alias egrep='egrep --color=auto'",
       "alias fgrep='fgrep --color=auto'",
       "alias path='echo -e ${PATH//:/\\n}'"].join("\n")
    )
    file.write_file

    file.insert_line_if_no_match(
      '# OpenStudio Server aliases. Generated by Chef',
      ["\n# OpenStudio Server aliases. Generated by Chef",
       "alias cs='/data/launch-instance/configure_vagrant_server.sh'",
       "alias cw='/data/launch-instance/configure_vagrant_worker.sh'",
       "alias cwd='/data/launch-instance/configure_vagrant_worker_data.sh'",
       "alias td='tail -f /var/www/rails/openstudio/log/development.log'",
       "alias tm='tail -f /var/www/rails/openstudio/log/mongo.log'",
       "alias tr='tail -f /var/www/rails/openstudio/log/Rserve.log'",
       "alias oo='Rscript /var/www/rails/openstudio/lib/Rscripts/OptimOutput.R'",
       "alias cdr='cd /var/www/rails/openstudio'"].join("\n")
    )
    file.write_file

    # Set the permissions on the file
    FileUtils.chown(node[:openstudio_server][:bash_profile_user], node[:openstudio_server][:bash_profile_user], bash_filename)
  end
end
