# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  is_windows = (RUBY_PLATFORM =~ /mswin|mingw|cygwin/)
  use_nfs = !is_windows
  use_nfs = false if ENV["VAGRANT_DISABLE_NFS"] == "true"

  config.omnibus.chef_version = :latest

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu-precise-64-vbox"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  #config.vm.network :forwarded_port, guest: 27017, host: 8888
  config.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.11"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  #update guest addition to latest virtualbox (requires vagrant-vbguest plugin)
  config.vbguest.auto_reboot = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder "../../", "/vagrant", :nfs => !is_windows
  config.vm.synced_folder "../../worker-nodes", "/data/worker-nodes", type: "rsync", :mount_options => [ "dmode=777", "fmode=777" ], rsync__exclude: ".git/", :rsync__args => ["--verbose", "--archive", "--delete", "-z", "--chmod=a+rwx"]
  config.vm.synced_folder "../../launch-instance", "/data/launch-instance", type: "rsync", :mount_options => [ "dmode=777", "fmode=777" ], rsync__exclude: ".git/", :rsync__args => ["--verbose", "--archive", "--delete", "-z", "--chmod=a+rwx"]
  config.vm.synced_folder "../../lib/R-packages", "/data/R-packages", type: "rsync", :mount_options => [ "dmode=777", "fmode=777" ], rsync__exclude: ".git/", :rsync__args => ["--verbose", "--archive", "--delete", "-z", "--chmod=a+rwx"]
  config.vm.synced_folder "J:/data-worker", "/mnt/openstudio", type: "rsync", rsync__exclude: ".git/", :owner => "vagrant", :group => "www-data", :mount_options => [ "dmode=775", "fmode=775" ]

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    # vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", 1024*12*4, "--cpus", 12]
#	vb.customize ["modifyvm", :id, "--memory", 1024*21*4, "--cpus", 21]
    #vb.customize ["modifyvm", :id, "--memory", 1024*2, "--cpus", 1*2]

    # Disable DNS proxy.
    # Causes slowness: https://github.com/rubygems/rubygems/issues/513
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vm.hostname = "os-worker-1"

  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  config.vm.provision :chef_solo do |chef|
    chef.log_level = :info
    chef.cookbooks_path = "../chef/cookbooks"
    chef.roles_path = "../chef/roles"

    chef.add_role "openstudio-worker"
  end
end
