source 'http://rubygems.org'

gem 'rails', '3.2.13'

# data modules
gem 'json'

# database modules
gem 'mongoid'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'

# R
gem 'rserve-simpler'
gem 'uuid'

# javascript
gem 'libv8'
gem 'execjs'
gem 'therubyracer'

gem 'haml'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
  gem 'rspec'
  gem 'rspec-rails', '~> 2.0'

  gem 'rspec-html-matchers'
  gem 'factory_girl_rails'
end

# job queuing
gem 'delayed_job_mongoid'
gem 'daemons'



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
#gem 'ruby-debug' if RAILS_VERSION > "2.0.0"
