source 'http://rubygems.org'

gem 'rails', '3.2.22'

# data modules
gem 'json'
gem 'jbuilder'
gem 'rubyzip'

# database modules
gem 'mongoid', '~> 3.1.6'
gem 'paperclip', '~> 4.1.1'
gem 'mongoid-paperclip', require: 'mongoid_paperclip'

# R
gem 'rserve-simpler'

# net-*
gem 'net-http-persistent'
gem 'net-scp'
gem 'net-ssh'
gem 'net-sftp'

# javascript
gem 'libv8', :platforms => :ruby
gem 'execjs'
gem 'therubyracer', :platforms => :ruby

# other useful gems
gem 'parallel'
gem 'sys-filesystem'

# web ui
# gem 'will_paginate'
gem 'jquery-rails'
gem 'kaminari'

# job queuing
gem 'delayed_job_mongoid'
gem 'daemons'

# http(s) requests
gem 'faraday'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  # sass versions above 3.2.10 giving 'text file busy' error on vagrant windows
  gem 'sass', '3.2.10'
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'bootstrap-sass', '~> 2.3.2.2'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'sextant' # navigate to /rails/routes to see routes
  gem 'better_errors'
  gem 'meta_request'
  gem 'ruby-prof'
  # gem 'ruby-debug' if RAILS_VERSION > "2.0.0"

  gem 'rspec'
  gem 'rspec-rails'
  gem 'mongoid-rspec'
  gem 'rspec-html-matchers'
  gem 'factory_girl_rails'
  gem 'ci_reporter', '~> 1.9.0'

  # these two openstudio gems are needed for starting up the cluster
  # and running the analysis in the integration tests
  gem 'openstudio-aws'
  gem 'openstudio-analysis'
end

