source 'http://rubygems.org'
ruby '~>2.7.0'

# unclear if this will actually force this version of rubygems to be used
# if not, run the following command to change system gem version:
# gem update --system 2.7.8
# gem 'rubygems-update', '2.7.8'

gem 'rails', '~> 6.1.3'
gem 'rake', '~> 13.0'

# added for support of the project rakefile
gem 'colored'

# data modules
gem 'jbuilder', '~> 2.11.2'
gem 'nokogiri', '~> 1.11.7'
gem 'rubyzip', '~> 2.3.0'
gem 'tzinfo-data', '~>1.2021.1'
gem 'loofah',  '2.20.0'

# database modules
gem 'mongoid', '7.5.4'
gem 'mongoid-paperclip'

# R
gem 'rserve-simpler', '~> 0.0.6'

# net-*
gem 'net-http-persistent', '~> 4.0.1'
gem 'net-scp', '~> 1.2.1'
gem 'net-sftp', '~> 3.0.0'
gem 'net-ssh', '~> 6.1.0'

# other useful gems
gem 'parallel', '~> 1.19.1'
gem 'sys-filesystem', '~> 1.4.1'

# web ui
# gem 'will_paginate'
gem 'jquery-rails', '~> 4.4.0'
gem 'kaminari', '~> 1.2.1'
gem 'kaminari-mongoid', '~> 1.0.1'

# job queuing
gem 'daemons', '~> 1.3.1'

# Gems used only for assets and not required
# in production environments by default.
gem 'bootstrap-sass', '~> 3.4.1'
gem 'coffee-rails', '~> 5.0.0'
gem 'sass', '~> 3.7.4'
gem 'sass-rails', '~> 6.0.0'
gem 'sprockets-rails', '~> 3.2.2'
gem 'uglifier', '~> 4.2.0'
# mail => 2.8.0 has startup failures with rails 6.1.x series
gem 'mail', '= 2.7.1'
# don't try to install sassc 2.
gem 'roo', '~> 2.8.3'
gem 'sassc', '~> 2.4.0'

# For workers - and other dependencies for measures
## Commonly update gems for testing and development

gem 'openstudio-workflow', '= 2.3.1'
#gem 'openstudio-analysis', :github => 'NREL/OpenStudio-analysis-gem', :ref => 'develop'
gem 'openstudio-analysis', '= 1.3.5'

# Remove urbanopt cli gems for minor for releases as they use different versions of ext gems
gem 'urbanopt-cli', '= 0.9.2'
gem 'urbanopt-reopt', '= 0.9.0'

## End commonly updated gems

gem 'openstudio-aws'

# libxml 3.2.0 failing on windows
gem 'bson', '~> 4.12.0' # bson 4.6.0 requires ruby >= 2.3.0
#gem 'libxml-ruby'
gem 'msgpack', '~> 1.4.2'
gem 'multi_json', '~> 1.15.0'
gem 'nio4r', '~> 2.5.7'
gem 'rest-client', '~> 2.1.0'

# add to Gemfile to make available to Ruby scripts running via initialize/finalize scripts
gem 'rubyXL', '~> 3.4.17'

# linux based js runtime libraries
if RUBY_PLATFORM =~ /linux/
  gem 'execjs', '=2.7.0'
  gem 'libv8', '=3.16.14.19'
  gem 'therubyracer', '=0.12.3'
elsif RUBY_PLATFORM =~ /darwin/
  gem 'execjs', github: 'NREL/execjs'
end

# The only resque only is :docker, :docker-dev, :production
group :development, :docker, :'docker-dev', :'docker-test', :production, :test do
  gem 'redis', '~> 4.2.5'
  gem 'redis-namespace', '~> 1.8.1'
  gem 'resque', '~> 2.0.0'
  gem 'resque-web', '~> 0.0.12', require: 'resque_web'
end

group :development, :'docker-test', :test, :local, :'local-test' do
  gem 'delayed_job_mongoid', '~> 2.3.1'
end

group :development, :test do
  gem 'better_errors', '~> 2.9.1'
  gem 'meta_request', '~> 0.7.2'

  gem 'capybara', '~> 3.35.3'
  gem 'coveralls', '0.7.1', require: false
  gem 'public_suffix', '~> 4.0.6'
  gem 'puma', '~> 5.6.0' # used by capybara
  gem 'rspec', '~> 3.10.0'
  gem 'rspec-rails', '~> 5.0.1'
  gem 'rspec-retry', '~> 0.6.2'
  gem 'ruby-prof', '~> 1.4.3'
  gem 'selenium-webdriver', '~> 3.142.7'

  gem 'psych', '~> 3.3.1'
  gem 'rubocop', '~> 1.15.0'
  gem 'rubocop-checkstyle_formatter', '~> 0.4.0'
  gem 'rubocop-rspec', '~> 1.26.0'

  gem 'ci_reporter', '~> 2.0.0'
  gem 'factory_bot_rails', '~> 6.1.0'
  gem 'mongoid-rspec', '~> 4.1.0'
  gem 'rspec-html-matchers', '~> 0.9.4'

  gem 'json-schema', '~> 2.8.1'
end
