
source 'http://rubygems.org'

ruby '~> 2.5.0'

# Local gems are useful when developing and integrating the various dependencies.
# To favor the use of local gems, set the following environment variable:
#   Mac: export FAVOR_LOCAL_GEMS=1
#   Windows: set FAVOR_LOCAL_GEMS=1
# Note that if allow_local is true, but the gem is not found locally, then it will
# checkout the latest version (develop) from github.

# Uncomment the extension, core gems if you need to test local development versions. Otherwise
# these are included in the model articulation and urbanopt gems
#

gem 'openstudio-extension', '0.3.2'
gem 'urbanopt-core', '0.5.1'
gem 'openstudio-common-measures', '0.3.2'
gem 'openstudio-model-articulation', '0.3.1'
gem 'urbanopt-scenario', '0.5.0'
gem 'urbanopt-geojson', '0.5.1'
gem 'urbanopt-reporting', '0.3.2'