source 'http://rubygems.org'

# OpenStudio gem from github
gem 'openstudio-workflow', github: 'NREL/OpenStudio-workflow-gem', ref: 'c98e91a'

# Install other gems that are needed but not required by the workflow gem
gem 'facter', '~> 2.3.0' # TODO: deprecate?
gem 'ruby-prof'
gem 'parallel'
gem 'msgpack'
gem 'multi_json'
gem 'oj'
gem 'rserve-simpler'

# Gems required for Rails mongoid adapter
gem 'mongoid', '~> 3.1.6'
gem 'paperclip', '~> 4.1.1'
gem 'mongoid-paperclip', require: 'mongoid_paperclip'
gem 'delayed_job_mongoid'

# Gems required for 3rd party libraries
gem 'libxml-ruby'
gem 'os'
gem 'uuid' # convert this to SecureRandom internal ruby library
