# Install Packages
install.packages('lhs', repos='http://cran.r-project.org')
install.packages('e1071', repos='http://cran.r-project.org')
install.packages('triangle', repos='http://cran.r-project.org')
install.packages('rJava', repos='http://cran.r-project.org') # TODO: remove this and dependent libraries
install.packages('RUnit', repos='http://cran.r-project.org')
install.packages('RMongo', repos='http://cran.r-project.org') # TODO: remove this and dependent libraries
install.packages('R.methodsS3', repos='http://cran.r-project.org')
install.packages('R.oo', repos='http://cran.r-project.org')
install.packages('R.utils', repos='http://cran.r-project.org')
install.packages('NMOF', repos='http://cran.r-project.org')
install.packages('mco', repos='http://cran.r-project.org')
install.packages('rgenoud', repos='http://cran.r-project.org')
install.packages('conf.design', repos='http://cran.r-project.org')
install.packages('vcd', repos='http://cran.r-project.org')
install.packages('combinat', repos='http://cran.r-project.org')
install.packages('DoE.base', repos='http://cran.r-project.org')
install.packages('xts', repos='http://cran.r-project.org')
install.packages('rjson', repos='http://cran.r-project.org')
install.packages('RSQLite', repos='http://cran.r-project.org')
install.packages('Rcpp', repos='http://cran.r-project.org')
install.packages('plyr', repos='http://cran.r-project.org')
install.packages('ggplot2', repos='http://cran.r-project.org')
install.packages('sensitivity', repos='http://cran.r-project.org')
install.packages('Rserve', configure.args=c('PKG_CPPFLAGS=-DNODAEMON'), repos='http://cran.r-project.org')
