q# Install Packages
install.packages('lhs', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('e1071', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('triangle', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('RUnit', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('R.methodsS3', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('R.oo', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('R.utils', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('NMOF', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('mco', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('rgenoud', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('conf.design', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('vcd', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('combinat', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('DoE.base', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('xts', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('rjson', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('RSQLite', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('Rcpp', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('plyr', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('ggplot2', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('sensitivity', repos=c('http://cloud.r-project.org','http://cran.r-project.org'))
install.packages('Rserve', configure.args=c('PKG_CPPFLAGS=-DNODAEMON'), repos=c('http://rforge.net'))