# *******************************************************************************
# OpenStudio(R), Copyright (c) Alliance for Sustainable Energy, LLC.
# See also https://openstudio.net/license
# *******************************************************************************

# Pure-Ruby LHS sampler. Drop-in replacement for AnalysisLibrary::R::Lhs that
# does not require Rserve, so sampling works on `openstudio_meta start_local`
# deployments (PAT-style, no Docker/Redis/R). Mirrors the API and behavior of
# analysis_library/r/lhs.rb; histogram PreflightImages are not generated by
# this backend.
module AnalysisLibrary::Sampling
  class Lhs
    def initialize(seed = nil)
      @rng = seed.is_a?(Numeric) ? Random.new(seed.to_i) : Random.new
    end

    # Take the number of variables and number of samples and generate the bins for an LHS sample
    def lhs_probability(num_variables, sample_size)
      logger.info "Start generating of LHS #{Time.now}"
      o = Distributions.lhs_probability(num_variables, sample_size, @rng)
      logger.info "Finished generating of LHS #{Time.now}"
      o
    end

    # Sample the data in a discrete manner using the variable's values and weights.
    def discrete_sample_from_probability(probabilities_array, var)
      if var.map_discrete_hash_to_array.nil? || var.discrete_values_and_weights.empty?
        raise 'no hash values and weight passed'
      end

      values, weights = var.map_discrete_hash_to_array

      if var.uncertainty_type == 'bool' || var.uncertainty_type == 'boolean'
        raise 'bool distribution needs some updating to map from bools'
      elsif var.uncertainty_type != 'discrete'
        raise "discrete distribution type #{var.uncertainty_type} not known for Ruby sampling"
      end

      samples = Array(probabilities_array).map { |p| Distributions.q_discrete(p, weights, values) }
      logger.info("Ruby sampler created the following samples #{samples}")

      samples
    end

    # Transform the LHS probabilities into the target distribution via its quantile function.
    # Mirrors R::Lhs#samples_from_probability, including the out-of-bounds resample to a
    # uniform value for normal/lognormal.
    def samples_from_probability(probabilities_array, distribution_type, mean, stddev, min, max)
      logger.info 'Creating sample from probability'
      probabilities_array = Array(probabilities_array)

      min_f = min.to_f
      max_f = max.to_f
      samples = case distribution_type
                when 'normal'
                  probabilities_array.map { |p| Distributions.q_normal(p, mean.to_f, stddev.to_f) }
                when 'lognormal'
                  probabilities_array.map { |p| Distributions.q_lognormal(p, mean.to_f, stddev.to_f) }
                when 'uniform'
                  probabilities_array.map { |p| Distributions.q_uniform(p, min_f, max_f) }
                when 'triangle'
                  # R backend calls qtriangle(p, min, max, mean) where mean is the mode
                  probabilities_array.map { |p| Distributions.q_triangle(p, min_f, max_f, mean.to_f) }
                else
                  raise "distribution type #{distribution_type} not known for Ruby sampling"
                end

      # normal/lognormal are unbounded: replace out-of-range values with uniform draws (same as R)
      if %w(normal lognormal).include? distribution_type
        samples = samples.map do |s|
          (s > max_f) || (s < min_f) ? Distributions.q_uniform(@rng.rand, min_f, max_f) : s
        end
      end

      logger.info("Ruby sampler created the following samples #{samples}")
      samples
    end

    def sample_all_variables(selected_variables, number_of_samples)
      samples = {}
      var_types = []
      var_names = []
      min_max = {}
      min_max[:min] = []
      min_max[:max] = []
      min_max[:eps] = []

      # get the probabilities
      logger.info "Sampling #{selected_variables.count} variables with #{number_of_samples} samples"
      p = lhs_probability(selected_variables.count, number_of_samples)
      logger.info "Probabilities #{p.class} with #{p.inspect}"

      i_var = 0
      selected_variables.each do |var|
        if var.measure # measure is optional for a variable
          logger.info "sampling variable #{var.name} for measure #{var.measure.name}"
        else
          logger.info "sampling variable #{var.name}"
        end
        variable_samples = nil
        var_names << var.name
        if var.uncertainty_type == 'discrete'
          logger.info("discrete vars for #{var.name} are #{var.discrete_values_and_weights}")
          variable_samples = discrete_sample_from_probability(p[i_var], var)
          var_types << 'discrete'
        elsif var.uncertainty_type == 'integer_sequence_uncertain' || var.uncertainty_type == 'integer_sequence'
          logger.info("creating integer sequence by seq(from=#{var.lower_bounds_value}, to=#{var.upper_bounds_value}, by=#{var.modes_value})")
          values = Distributions.seq(var.lower_bounds_value, var.upper_bounds_value, var.modes_value)
          weights = Array.new(values.size, 1.0 / values.size)
          variable_samples = Array(p[i_var]).map { |prob| Distributions.q_discrete(prob, weights, values) }
          logger.info("Ruby sampler created the following samples #{variable_samples}")
          var_types << 'discrete'
        else
          variable_samples = samples_from_probability(p[i_var], var.uncertainty_type, var.modes_value, var.stddev_value,
                                                      var.lower_bounds_value, var.upper_bounds_value)
          var_types << 'continuous'
        end

        min_max[:min] << var.lower_bounds_value
        min_max[:max] << var.upper_bounds_value
        if var.delta_x_value
          min_max[:eps] << var.delta_x_value
        else
          min_max[:eps] << 0
        end

        samples[var.id.to_s] = variable_samples

        # NOTE: the R backend renders a histogram PreflightImage per variable here.
        # The Ruby backend intentionally skips plot generation (no R/cairo available).
        logger.info "Skipping preflight histogram for #{var.name} (Ruby sampling backend)"

        var.r_index = i_var + 1 # r_index is 1-based
        var.save!

        i_var += 1
      end

      [samples, var_types, min_max, var_names]
    end

    private

    def logger
      Rails.logger
    end
  end
end
