# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  is_windows = (RUBY_PLATFORM =~ /mswin|mingw|cygwin/)
  use_nfs = !is_windows
  use_nfs = false if ENV["VAGRANT_DISABLE_NFS"] == "true" 

  # Don't use 11.14.2 because of https://github.com/opscode/chef/issues/1739 (duplicate error)  
  # config.omnibus.chef_version = :latest
  config.omnibus.chef_version = "11.12.8"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 443, host: 8081
  config.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh"
  config.vm.network :forwarded_port, guest: 3000, host: 8082
  config.vm.network :forwarded_port, guest: 27017, host: 8888

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network
  
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../server", "/var/www/rails/openstudio", :nfs => use_nfs
  config.vm.synced_folder "../../worker-nodes", "/data/worker-nodes", :nfs => use_nfs
  config.vm.synced_folder "../../launch-instance", "/data/launch-instance", :nfs => use_nfs
  config.vm.synced_folder "../../lib/R-packages", "/data/R-packages", :nfs => use_nfs
  #config.vm.synced_folder "E:/data-server", "/mnt/openstudio", :nfs => use_nfs, :owner => "vagrant", :group => "www-data", :mount_options => [ "dmode=775", "fmode=775" ]

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    # vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", 2048, "--cpus", 2]

    # Disable DNS proxy.
    # Causes slowness: https://github.com/rubygems/rubygems/issues/513
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vm.hostname = "os-server"

  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  config.vm.provision :chef_solo do |chef|
    chef.log_level = :info
    chef.cookbooks_path = "../chef/cookbooks"
    chef.roles_path = "../chef/roles"

    chef.add_role "openstudio-server"
  end
end
